### ISSUE TITLE
Change input directory behavior to render recursively

### ISSUE THREAD

**Issue by aviadhaham** [orellazri/renderkit#29]
It's exactly what Gomplate allows me to use right now and what I'm using currently in "prod".
It's a must, actually.
ref: https://docs.gomplate.ca/config/#inputdir

that way, providing an `--input-dir` will render all the files recursively, no matter how deep
and the output would be inside the `--output-dir` with the same structure

In the current situation, it reads and tries to render the subdirectory as if it's a file
![Screenshot 2024-06-12 at 18 22 17](https://github.com/orellazri/renderkit/assets/76651338/47fefd1c-3c0d-4016-80ee-69f19b42419c)

Example of the desired behavior:
```
in/
├── dir1/
│    └── dir1file1.tpl
├── dir2/
│    └── dir2file2.tpl
└── file.tpl
```
```
out/
├── dir1/
│    └── dir1file1.tpl
├── dir2/
│    └── dir2file2.tpl
└── file.tpl
```

@orellazri

**Comment by orellazri** [comment]
@aviadhaham 
sounds like a great idea, but a design choice has to be made. we can either approach this with a default behavior or recursion, and then add a flag for disabling it, or vice-versa.
another good approach could be revamping the input flag to accept wildcards, so then an --input-dir flag will not be needed
