### ISSUE TITLE
Add version to CLI usage

### ISSUE THREAD

**Issue by orellazri** [orellazri/renderkit#57]
Both as a flag and in the help text.
This is probably natively supported in `urfave/cli`

**Comment by aviadhaham** [comment]
@orellazri 
seems like the version itself, including the `-v / --version` flag comes built in with `urfave/cli` and it's as easy as just adding `Version` to the `App`:
```
	app := &cli.App{
		Name:    "renderkit",
		...
		Version: "0.2.0",
		...
	}
```

```bash
$ go run main.go -v                                          
renderkit version 0.2.0
```

As for automating the version bump, seems like `gomplate` does this using his own logic written in go as well
https://github.com/hairyhenderson/gomplate/blob/e3b86e89fca0aad9f5a4f9856f0b57d9cc693470/version/gen/vgen.go

however, I did find this tool that seems interesting: https://github.com/restechnica/semverbot
