### ISSUE TITLE
Loading .env file

### ISSUE THREAD

**Issue by bersace** [orellazri/renderkit#67]
Hi,

What do you think of supporting `.env` file ? I use this in https://github.com/dalibo/ldap2pg to load secrets. I'm ok to contribute.

Regards,
Étienne

**Comment by orellazri** [comment]
Hey @bersace ! We support `.env` files already, see the description and example in [this part of the README](https://github.com/orellazri/renderkit?tab=readme-ov-file#notes-on-datasource).

Let me know if that's what you meant

**Comment by bersace** [comment]
Ok, it's explicit env file support. That's fine. Thanks for the pointer !
