### ISSUE TITLE
Relation to gomplate

### ISSUE THREAD

**Issue by bersace** [orellazri/renderkit#68]
Hi,

I just discovered https://github.com/hairyhenderson/gomplate. It looks on the same market as renderkit. Could you compare this for casual ?

Regards,
Étienne

**Comment by orellazri** [comment]
Hi
Gomplate is a really great project in the same field. We took inspiration from it and used it ourselves, but we wanted more (e.g. several template engines)
Gomplate is very mature and packed of features so comparing all features will not be trivial :)

**Comment by ccoVeille** [comment]
This is an interesting information you could add the README file.

I always find meaningful when project inspiration are provided on the page project.

It helps to understand quickly why the project exists and how it differs from others
